/* This is the query copied from original data with baraa material:
/*
===============================================================================
DDL Script: Create Bronze Tables
===============================================================================
Script Purpose:
    This script creates tables in the 'bronze' schema, dropping existing tables 
    if they already exist.
	  Run this script to re-define the DDL structure of 'bronze' Tables
===============================================================================
*/
/*
IF OBJECT_ID('bronze.crm_cust_info', 'U') IS NOT NULL
    THEN DROP TABLE bronze.crm_cust_info;

CREATE TABLE bronze.crm_cust_info (
    cst_id              INT,
    cst_key             NVARCHAR(50),
    cst_firstname       NVARCHAR(50),
    cst_lastname        NVARCHAR(50),
    cst_marital_status  NVARCHAR(50),
    cst_gndr            NVARCHAR(50),
    cst_create_date     DATE
)
*/
/* the following query generated by gemini does not work, due to lack of bronze dataset. 
Big query use dataset to perform function of schema from sql server.
DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.crm_cust_info`;
CREATE TABLE `data-with-baraa-sql-projects.bronze.crm_cust_info`
(
  cst_id INT64,
  cst_key STRING,
  cst_firstname STRING,
  cst_lastname STRING,
  cst_marital_status STRING,
  cst_gndr STRING,
  cst_create_date DATE
);
*/

CREATE SCHEMA IF NOT EXISTS `data-with-baraa-sql-projects.bronze`;

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.crm_cust_info`;
CREATE TABLE `data-with-baraa-sql-projects.bronze.crm_cust_info`
  (
  cst_id INT64,
  cst_key STRING,
  cst_firstname STRING,
  cst_lastname STRING,
  cst_marital_status STRING,
  cst_gndr STRING,
  cst_create_date DATE
  );

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.crm_prd_info`;
CREATE TABLE `data-with-baraa-sql-projects.bronze.crm_prd_info`
  (
    prd_id       INT64,
    prd_key      STRING,
    prd_nm       STRING,
    prd_cost     INT64,
    prd_line     STRING,
    prd_start_dt DATETIME,
    prd_end_dt   DATETIME
  );

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.crm_sales_details`;
CREATE TABLE bronze.crm_sales_details 
  (
    sls_ord_num  STRING,
    sls_prd_key  STRING,
    sls_cust_id  INT64,
    sls_order_dt INT64,
    sls_ship_dt  INT64,
    sls_due_dt   INT64,
    sls_sales    INT64,
    sls_quantity INT64,
    sls_price    INT64
  );

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.erp_loc_a101`;
CREATE TABLE bronze.erp_loc_a101 
  (
    cid    STRING,
    cntry  STRING
  );

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.erp_cust_az12`;
CREATE TABLE bronze.erp_cust_az12 
  (
    cid    STRING,
    bdate  DATE,
    gen    STRING
  );

DROP TABLE IF EXISTS `data-with-baraa-sql-projects.bronze.erp_px_cat_g1v2`; 
CREATE TABLE bronze.erp_px_cat_g1v2 
  (
    id           STRING,
    cat          STRING,
    subcat       STRING,
    maintenance  STRING
  );